@IMS.WebApi_HostAddress = https://localhost:7282
@token = 

### signin enpoint

POST {{IMS.WebApi_HostAddress}}/api/users/signin
Content-Type: application/json


###

### create-admin enpoint (role must be SuperAdmin or Admin)
POST {{IMS.WebApi_HostAddress}}/api/users/create-admin
Content-Type: application/json
Authorization: Bearer {{token}}


###